user_command_timeout: 0.4 # [s]

start_land_velocity: 0.5 # [m/s]
start_height: 1.0 # [m]

propeller_ramp_down_timeout: 1.5 # [s]
idle_thrust: 2.0 # [m/s]
start_idle_duration: 2.0 # [s]

optitrack_start_land_timeout: 10 # [s]
optitrack_land_drop_height: 0.3 # [m]

open_loop_takeoff_timeout: 1.0 # [s]
vision_init_timeout: 2.0 # [s]
open_loop_takeoff_thrust: 12.0 # [m/s^2]
vision_land_drop_height: 0.35 # [m]
  
emergency_land_duration: 6   # [s]
emergency_land_thrust: 9.0 # [m/s^2]

breaking_velocity_threshold: 0.2 # [m/s]
breaking_timeout: 1.0 # [s]

manual_velocity_input_timeout: 0.1 # [s]
tau_manual_velocity: 0.8 # []
  